#!/usr/bin/env python3
"""Build ClaudeRestart.exe and ClaudeRestart-quiet.exe with PyInstaller.

Steps: install the pinned build tools (unless --no-install), run the unit tests,
regenerate the icon, run PyInstaller on ClaudeRestart.spec, smoke-test both
executables, then zip the release layout into dist/. Windows, Python 3.10+.
read_version() is the single place the version is read (clauderestart/__init__.py);
ClaudeRestart.spec imports it from here. The payload (executables and release files)
is defined once in clauderestart/payload.py and imported here, by the spec, and by
the application itself, so adding a file cannot create two diverging manifests.

    py -3 build.py
    py -3 build.py --no-install --skip-tests
    py -3 build.py --check-tag v1.0.0     # only verifies the tag matches __version__
"""

from __future__ import annotations

import argparse
import ast
import collections
import hashlib
import importlib.util
import json
import os
from pathlib import Path
import re
import shutil
import subprocess
import sys
import time
import zipfile


ROOT = Path(__file__).resolve().parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from clauderestart import payload  # noqa: E402  (pure Python, safe to import on any platform)

DIST = ROOT / "dist"
SOURCE = ROOT / "clauderestart" / "__init__.py"
EXECUTABLES = payload.EXECUTABLES
RELEASE_FILES = payload.RELEASE_FILES
TWIN_MODULE = ROOT / "clauderestart" / "_twin.py"
BUILD_TARGET_ENV = "CLAUDERESTART_BUILD_TARGET"
MANIFEST_NAME = "release-manifest.json"
ZIP_EPOCH_FLOOR = 315532800  # 1980-01-01, the oldest timestamp a ZIP entry can carry


# What the console build is told about the windowed twin built just before it.
# A namedtuple, not a dataclass: ClaudeRestart.spec and the tests load this file by
# path, and dataclasses resolve field types through sys.modules, which a by-path load
# does not populate.
TwinRecord = collections.namedtuple("TwinRecord", "name sha256 size version")


def read_version() -> str:
    match = re.search(r'^__version__\s*=\s*"([^"]+)"', SOURCE.read_text(encoding="utf-8"), re.M)
    if not match:
        sys.exit("__version__ not found in clauderestart/__init__.py")
    return match.group(1)


def run(command: list[str], **kwargs: object) -> subprocess.CompletedProcess[str]:
    print("+", subprocess.list2cmdline(command), flush=True)
    return subprocess.run(command, cwd=ROOT, check=True, text=True, **kwargs)  # type: ignore[call-overload]


def write_twin_module(record: TwinRecord | None) -> None:
    """Write clauderestart/_twin.py: the placeholder, or the real twin record.

    The placeholder is what the repository always holds; a real record exists only
    between the two PyInstaller stages, and is restored to the placeholder afterwards.
    """
    if record is None:
        text = (
            '"""Placeholder twin record; build.py writes the real one between build stages."""\n'
            "\n"
            "TWIN_NAME = None\n"
            "TWIN_SHA256 = None\n"
            "TWIN_SIZE = 0\n"
            "TWIN_VERSION = None\n"
        )
    else:
        text = (
            '"""Generated by build.py: the windowed twin this console build was made with."""\n'
            "\n"
            f'TWIN_NAME = "{record.name}"\n'
            f'TWIN_SHA256 = "{record.sha256}"\n'
            f"TWIN_SIZE = {record.size}\n"
            f'TWIN_VERSION = "{record.version}"\n'
        )
    TWIN_MODULE.write_text(text, encoding="utf-8", newline="\n")
    # Drop any compiled copy: the two build stages rewrite this file seconds apart, and
    # Python's bytecode cache keys on whole-second mtime plus size, so a same-second
    # rewrite of the same length would otherwise be served from the stale cache.
    for stale in TWIN_MODULE.parent.glob("__pycache__/_twin.*.pyc"):
        stale.unlink(missing_ok=True)


def read_twin_module() -> TwinRecord | None:
    """Read the generated record, or None when it is absent or still a placeholder.

    The file is parsed, never imported: importing it would go through the bytecode cache
    described above, and a stale read here would let a console build ship a record of a
    twin it was not built with.
    """
    if not TWIN_MODULE.is_file():
        return None
    values: dict[str, object] = {}
    for node in ast.parse(TWIN_MODULE.read_text(encoding="utf-8")).body:
        if isinstance(node, ast.Assign) and len(node.targets) == 1 and isinstance(node.targets[0], ast.Name):
            try:
                values[node.targets[0].id] = ast.literal_eval(node.value)
            except ValueError:
                continue
    digest = values.get("TWIN_SHA256")
    if not digest:
        return None
    return TwinRecord(
        str(values.get("TWIN_NAME") or ""),
        str(digest),
        int(values.get("TWIN_SIZE") or 0),
        str(values.get("TWIN_VERSION") or ""),
    )


def twin_record_for_target(target: str, dist: Path | None = None) -> TwinRecord | None:
    """Validate the twin record for the stage the spec is about to build.

    ClaudeRestart.spec calls this, so a console executable can never be produced without
    a real record (it could then never install), and the windowed twin can never carry a
    stale record of a previous build.
    """
    dist = DIST if dist is None else dist
    if target not in ("quiet", "console"):
        sys.exit(
            f"{BUILD_TARGET_ENV} must be 'quiet' or 'console'. ClaudeRestart.spec is driven by build.py; "
            "run: py -3 build.py"
        )
    record = read_twin_module()
    if target == "quiet":
        if record is not None:
            sys.exit(
                "clauderestart/_twin.py still holds a twin record, which the windowed build must not carry. "
                "Run: py -3 build.py"
            )
        return None
    if record is None:
        sys.exit(
            "The console build needs the record of its windowed twin, which build.py writes between stages. "
            "Run: py -3 build.py"
        )
    current = read_version()
    if record.version != current:
        sys.exit(f"The twin record is for version {record.version}, but this source is {current}. Run: py -3 build.py")
    built = dist / record.name
    if not built.is_file():
        sys.exit(
            f"The console stage has no windowed twin at {built} to check its record against, so the "
            "record cannot be trusted. Run: py -3 build.py"
        )
    digest, size = sha256(built), built.stat().st_size
    if digest != record.sha256 or size != record.size:
        sys.exit(f"The twin record does not match {built}; the stages ran out of order. Run: py -3 build.py")
    return record


def stage_environment(target: str) -> dict[str, str]:
    """Environment for one PyInstaller stage: which target, and reproducible inputs."""
    env = dict(os.environ)
    env[BUILD_TARGET_ENV] = target
    env["PYTHONHASHSEED"] = "0"
    env.setdefault("SOURCE_DATE_EPOCH", str(source_date_epoch()))
    return env


def source_date_epoch() -> int:
    """A fixed timestamp for archive entries: the environment's, else the last commit."""
    value = os.environ.get("SOURCE_DATE_EPOCH", "")
    if value.isdigit():
        return int(value)
    try:
        completed = subprocess.run(
            ["git", "log", "-1", "--format=%ct"],
            cwd=ROOT,
            capture_output=True,
            text=True,
            check=False,
        )
    except OSError:
        return ZIP_EPOCH_FLOOR
    stamp = completed.stdout.strip()
    return int(stamp) if completed.returncode == 0 and stamp.isdigit() else ZIP_EPOCH_FLOOR


def build_executables(python: str, version: str) -> TwinRecord:
    """Build the windowed twin, embed its digest, then build the console executable.

    The console executable is the trust root for the twin, so it must be built second,
    from a record of the exact twin bytes that shipped with it.
    """
    spec_path = str(ROOT / "ClaudeRestart.spec")
    write_twin_module(None)
    try:
        run([python, "-m", "PyInstaller", "--clean", "--noconfirm", spec_path], env=stage_environment("quiet"))
        quiet_exe = DIST / payload.QUIET_EXE_NAME
        if not quiet_exe.is_file():
            sys.exit(f"PyInstaller did not produce {payload.QUIET_EXE_NAME}.")
        record = TwinRecord(payload.QUIET_EXE_NAME, sha256(quiet_exe), quiet_exe.stat().st_size, version)
        write_twin_module(record)
        run([python, "-m", "PyInstaller", "--noconfirm", spec_path], env=stage_environment("console"))
        return record
    finally:
        # The repository never carries a real record, whether or not the build succeeded.
        write_twin_module(None)


def build_zip(archive: Path, timestamp: int) -> None:
    """Write the release ZIP deterministically: fixed member order and timestamps."""
    stamp = time.gmtime(max(timestamp, ZIP_EPOCH_FLOOR))
    date_time = (stamp.tm_year, stamp.tm_mon, stamp.tm_mday, stamp.tm_hour, stamp.tm_min, stamp.tm_sec)
    members = [(DIST / name, name) for name in EXECUTABLES]
    members.extend((ROOT / relative, relative) for relative in RELEASE_FILES)
    with zipfile.ZipFile(archive, "w", compression=zipfile.ZIP_DEFLATED) as bundle:
        for source_file, name in sorted(members, key=lambda item: item[1]):
            info = zipfile.ZipInfo(name, date_time=date_time)
            info.compress_type = zipfile.ZIP_DEFLATED
            info.external_attr = 0o644 << 16
            bundle.writestr(info, source_file.read_bytes())


def write_release_manifest(dist: Path, version: str, record: TwinRecord) -> Path:
    """Record every asset a release must carry, with its digest, size, and commit.

    The release workflow compares this with what GitHub reports, so the published bytes
    are tied to the commit that produced them.
    """
    assets = []
    for name in payload.release_asset_names(version):
        path = dist / name
        if not path.is_file():
            sys.exit(f"Cannot write {MANIFEST_NAME}: {name} is missing from {dist}.")
        assets.append({"name": name, "sha256": sha256(path), "size": path.stat().st_size})
    manifest = {
        "version": version,
        "tag": f"v{version}",
        "commit": os.environ.get("GITHUB_SHA") or None,
        "ref": os.environ.get("GITHUB_REF") or None,
        "embedded_twin": {"name": record.name, "sha256": record.sha256, "size": record.size},
        "assets": assets,
    }
    target = dist / MANIFEST_NAME
    target.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8", newline="\n")
    return target


def smoke_test(dist: Path, expected_version: str, record: TwinRecord | None = None) -> None:
    """Exercise both executables; exit with a message on any failure.

    The console build must print the expected version, pass --self-check, and report an
    embedded twin record equal to the twin that was actually built. The windowed build
    has no console output, so it is judged by its exit code and by the last-run.log it
    must write beside itself, which must show that it carries no record of its own.
    """
    console_exe = dist / EXECUTABLES[0]
    quiet_exe = dist / EXECUTABLES[1]
    for name in EXECUTABLES:
        if not (dist / name).is_file():
            sys.exit(f"PyInstaller did not produce {name}.")
    shown = run([str(console_exe), "--version"], capture_output=True).stdout.strip()
    if expected_version not in shown:
        sys.exit(f"Smoke test failed: '{shown}' does not contain {expected_version}.")
    self_check = run([str(console_exe), "--self-check"], capture_output=True).stdout
    if "SELF-CHECK" not in self_check:
        sys.exit("Smoke test failed: the console self-check printed no result.")
    if "race guards 5/5" not in self_check:
        sys.exit(f"Smoke test failed: the console self-check did not pass every race guard: {self_check.strip()}")
    print(self_check.strip().splitlines()[0], flush=True)
    if record is not None:
        printed = run([str(console_exe), "--print-embedded-twin"], capture_output=True).stdout.strip()
        expected = f"{record.name} {record.sha256} {record.size} {record.version}"
        if expected not in printed:
            sys.exit(f"Smoke test failed: embedded twin '{printed}' is not the twin that was built: '{expected}'.")
    log = dist / "last-run.log"
    if log.is_file():
        log.unlink()
    print("+", subprocess.list2cmdline([str(quiet_exe), "--self-check"]), "(windowed, no output expected)", flush=True)
    quiet = subprocess.run([str(quiet_exe), "--self-check"], cwd=ROOT, check=False)
    if quiet.returncode != 0:
        sys.exit(f"Smoke test failed: {quiet_exe.name} --self-check exited {quiet.returncode}.")
    if not log.is_file() or "SELF-CHECK" not in log.read_text(encoding="utf-8"):
        sys.exit(f"Smoke test failed: {quiet_exe.name} did not write {log.name} beside itself.")
    print(log.read_text(encoding="utf-8").strip().splitlines()[-1], flush=True)
    log.unlink()
    if record is not None:
        subprocess.run([str(quiet_exe), "--print-embedded-twin"], cwd=ROOT, check=False)
        carried = log.read_text(encoding="utf-8") if log.is_file() else ""
        if "none" not in carried:
            sys.exit(f"Smoke test failed: {quiet_exe.name} carries a twin record; it must carry none.")
        if log.is_file():
            log.unlink()


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1 << 20), b""):
            digest.update(chunk)
    return digest.hexdigest()


def main() -> int:
    parser = argparse.ArgumentParser(description="Build the ClaudeRestart executables.")
    parser.add_argument("--no-install", action="store_true", help="do not pip install requirements-build.txt")
    parser.add_argument("--skip-tests", action="store_true", help="do not run the unit tests first")
    parser.add_argument("--skip-icon", action="store_true", help="do not regenerate assets/ClaudeRestart.ico")
    parser.add_argument("--check-tag", metavar="TAG", help="exit 1 unless TAG equals 'v' + __version__, then stop")
    args = parser.parse_args()

    current = read_version()
    if args.check_tag is not None:
        expected = f"v{current}"
        if args.check_tag != expected:
            sys.exit(f"Tag {args.check_tag!r} does not match __version__ ({expected}).")
        print(f"Tag {args.check_tag} matches __version__.")
        return 0

    if os.name != "nt":
        sys.exit("The executables can only be built on Windows.")
    if sys.version_info < (3, 10):
        sys.exit("Python 3.10 or newer is required.")

    python = sys.executable
    if not args.no_install:
        run([python, "-m", "pip", "install", "--disable-pip-version-check", "-r", "requirements-build.txt"])
    if not args.skip_tests:
        run([python, "-m", "unittest", "discover", "-s", "tests", "-v"])
    if not args.skip_icon:
        run([python, str(ROOT / "tools" / "make_icon.py")])

    for stale in (DIST, ROOT / "build"):
        shutil.rmtree(stale, ignore_errors=True)
    record = build_executables(python, current)

    smoke_test(DIST, current, record)

    archive = DIST / payload.release_zip_name(current)
    build_zip(archive, source_date_epoch())

    checksums = DIST / payload.CHECKSUMS_NAME
    lines = [f"{sha256(DIST / name)}  {name}" for name in (*EXECUTABLES, archive.name)]
    checksums.write_text("\n".join(lines) + "\n", encoding="utf-8")
    manifest = write_release_manifest(DIST, current, record)
    print("\n".join(lines))
    print(f"\nBuilt {archive}")
    print(f"Wrote {manifest}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
